os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
before_script:
  - npm install --ignore-scripts
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm run clean
  - npm run build-ts
  - npm run build-cpp
  - npm test